IF NOT EXISTS (SELECT 1 FROM SYS.SCHEMAS WHERE NAME = 'restGenerator')
BEGIN
	EXEC('CREATE SCHEMA [restGenerator]')
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Api' AND TABLE_SCHEMA = 'restGenerator')
BEGIN
	CREATE TABLE [restGenerator].[Api]
	(
		[Id]			UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Api_Id] DEFAULT (NEWSEQUENTIALID()),
		[Name]			NVARCHAR(50) NOT NULL,
		[EncryptionKey]	NVARCHAR(99) NOT NULL,
		[DecryptionKey]	NVARCHAR(99) NOT NULL,
		[IsActive]		BIT NOT NULL,
		CONSTRAINT [PK_Api] PRIMARY KEY CLUSTERED ([Id] ASC),
		CONSTRAINT [UK_Api] UNIQUE ([Name])
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Resource' AND TABLE_SCHEMA = 'restGenerator')
BEGIN
	CREATE TABLE [restGenerator].[Resource]
	(
		[Id]	UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Resource_Id] DEFAULT (NEWSEQUENTIALID()),
		[ApiId]	UNIQUEIDENTIFIER NOT NULL,
		[Name]	NVARCHAR(50) NOT NULL,
		CONSTRAINT [PK_Resource] PRIMARY KEY CLUSTERED ([Id] ASC),
		CONSTRAINT [UK_Resource] UNIQUE ([Name])		
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [restGenerator].[Resource] WITH CHECK
	ADD CONSTRAINT [FK_Resource_Api] FOREIGN KEY ([ApiId])
	REFERENCES [restGenerator].[Api] ([Id])
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Field' AND TABLE_SCHEMA = 'restGenerator')
BEGIN
	CREATE TABLE [restGenerator].[Field]
	(
		[Id]			UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Field_Id] DEFAULT (NEWSEQUENTIALID()),
		[ResourceId]	UNIQUEIDENTIFIER NOT NULL,
		[Name]			NVARCHAR(50) NOT NULL,
		[Type]			INT NOT NULL,
		[IsEncrypted]	BIT NOT NULL,
		[IsRequired]	BIT NOT NULL,
		[IsUnique]		BIT NOT NULL,
		CONSTRAINT [PK_Field] PRIMARY KEY CLUSTERED ([Id] ASC),
		CONSTRAINT [UK_Field] UNIQUE ([Name])
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [restGenerator].[Field] WITH CHECK
	ADD CONSTRAINT [FK_Field_Resource] FOREIGN KEY ([ResourceId])
	REFERENCES [restGenerator].[Resource] ([Id])
END
